### ISSUE TITLE
directory copy exception 

### ISSUE THREAD

**Issue by Luke2706** [Louis9902/Sosse19-SE#13]
```
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\tmp\target\GdI'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at TinyTasksKit.Worker.SyncWorker.OnRenameFileEvent(Object sender, RenamedEventArgs args)
   at TinyTasksKit.Worker.SyncWorker.OnCommonFileEvent(Object sender, FileSystemEventArgs args)
   at System.IO.FileSystemWatcher.OnRenamed(RenamedEventArgs e)
   at System.IO.FileSystemWatcher.NotifyRenameEventArgs(WatcherChangeTypes action, String name, String oldName)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

**Comment by Louis9902** [comment]
Further Information required, which files are copied from where to where.
